name: "Cypress spec group generator"
description: "Generates spec groups for N parallel Cypress runs"
inputs:
  count:
    description: "Num of parallel runs"
    required: true
  tests:
    description: "Path to the tests folder"
    default: "cypress/**/*.(jsx?|tsx?)"
  results:
    description: "Path to the folder where the test results are stored"
    default: "results/**/*.xml"

outputs:
  result:
    description: "Spec groups"
runs:
  using: node16
  main: index.js
