on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    name: A job to transfer issues
    steps:
      - name: Find issues in commit messages
        id: find-issues
        uses: Agro-Club/github-actions/commit-messages-parser@master
        with:
          commits: "${{ github.event.commits }}"

      - name: Transfer issues
        uses: Agro-Club/github-actions/jira-webhook-call@master
        with:
          issues: ${{ steps.find-issues.outputs.entries }}
          url: https://automation.atlassian.com/pro/hooks/a422ff5cbb14832fad9502fef38ef7e30c8f9457
