on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    name: A job to transfer issues
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Find issues in commit messages
        id: find-issues
        uses: Agro-Club/github-actions/commit-messages-parser@master
        with:
          head: ${{ github.event.after }}
          base: ${{ github.event.before }}

      - name: Transfer issues
        uses: Agro-Club/github-actions/jira-multiple-issue-update@master
        with:
          issues: ${{ steps.find-issues.outputs.entries }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-username: ${{ secrets.JIRA_EMAIL }}
          jira-url: https://agroclub.atlassian.net
          request-body: '{"fields":{"customfield_10060": "${{ steps.date.outputs.date }}"}}'
