on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    name: A job to transfer issues
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find issues in commit messages
        id: find-issues
        uses: Agro-Club/github-actions/spec-group-generator@master
        with:
          count: 5
          tests: "!(node_modules)/**/*.*(js|ts|jsx|tsx)"
          results: "spec-group-generator/example-results/**/*.xml"
